### ISSUE TITLE
Flesh out Preview and Release workflows

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#13]
## Description

Issue #2 is going to be used to create the basic shell for the `Preview` and `Release` workflows. That is, they will be no-ops, but with the `workflow_dispatch` trigger set to enable iteration within a branch to get them where they need to be. This issue is meant to flesh out these workflows to their desired end state.

## Additional Details

* The `Preview` workflow will be used to
  * create a dev version and related package artifacts
  * optionally upload the package artifacts to TestPyPI
  * enable Staging-style testing before pushing to production
* The `Release` workflow will be used to
  * create a release version and related package artifacts
  * create a GitHub release with the package artifacts
    * Ensure the change log is updated and included in the release
  * upload the package artifacts to PyPI
* Consider using repository environments
  * for separation of secrets
  * for enabling manual approval, by group, of release and deployment actions 

## Acceptance Criteria

- [ ] `Preview` workflow is available for manual and automatic usage, with features outlined above
- [ ] `Release` workflow is available for automatic usage, with features outlined above
- [ ] Documentation is updated

**Comment by kylewillmon** [comment]
I'm not sure it makes sense to have a workflow that publishes to TestPyPI. That server is more meant for testing packaging tools. Pre-release packages should still be published to PyPI, but with a version number that indicates that they are a pre-release (according to PEP 440)
