### ISSUE TITLE
Extend Azure Pipelines integration to support GitHub repos

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#148]
## Overview

Initial Azure Pipelines support was added with #116, but only for git repositories hosted on Azure Repos. This issue is to extend the Azure Pipelines integration to support git repositories hosted on GitHub and pull requests (PRs) initiated from GitHub. The PRs should be analyzed and annotated automatically with the integration when they include changes to a lockfile.

## Additional context

* The cloud-hosted _Services_ version of Azure DevOps should be supported
  * The Azure DevOps _Server_ versions are [not supported for GitHub hosted repos](https://learn.microsoft.com/azure/devops/pipelines/repos)
* This iteration will support Azure DevOps Services, for code hosted in GitHub
  * It will only support git repositories
  * It will only support Pull Request triggers and will add comments to the PR in GitHub
* The [phylum-dev/phylum-analyze-pr-action](https://github.com/phylum-dev/phylum-analyze-pr-action) repository is the current working implementation for GitHub
* There is also a current working implementation for GitHub in the `phylum-ci` repo that can be used as a model
* Automated testing is not part of this effort
  * Manual testing should be performed at least
  * There will be a separate epic/story/issue to cover test automation for integrations
* Make use of the existing `phylum-ci` integration framework
* [Build GitHub Repositories](https://learn.microsoft.com/azure/devops/pipelines/repos/github)
  * Take a close look at the CI and PR triggers sections there
* [Predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables) of interest
  * `Build.Repository.Provider`
    * Look for `GitHub`
  * `BUILD_REPOSITORY_NAME` to get the `{owner}/{repo}` part needed for the GitHub comments API
  * `Build.SourceBranch` and/or `Build.SourceBranchName`
  * `Build.SourceVersion`
  * `System.AccessToken`
  * `System.PullRequest.PullRequestId` and `System.PullRequest.PullRequestNumber`
    * Use [`SYSTEM_PULLREQUEST_PULLREQUESTID`](https://github.com/watson/ci-info/blob/master/vendors.json) to determine when in a PR (vs. a "CI Trigger")
    * `SYSTEM_PULLREQUEST_PULLREQUESTNUMBER` is populated for pull requests from GitHub which have a different pull request ID and pull request number
      * Use this for the `{issue_number}` part needed for the GitHub comments API
  * `System.TeamFoundationCollectionUri`
    * Use [`SYSTEM_TEAMFOUNDATIONCOLLECTIONURI`](https://github.com/watson/ci-info/blob/master/vendors.json) to determine when in an Azure Pipelines environment
  * `System.PullRequest.SourceBranch`
  * `System.PullRequest.SourceRepositoryURI`
    * Use `SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI` to distinguish between the possible sources where the PR is hosted (e.g., Azure Repos, GitHub, or Bitbucket)
  * `System.PullRequest.TargetBranch`
* [Define variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)

## Acceptance criteria

- [x] The `phylum` package offers the ability to analyze lockfile changes in the ADO Services CI ecosystem for repositories hosted on GitHub
  - [x] The PRs created in GitHub are commented by `phylum`, like for the existing GitHub integration
- [x] Documentation is updated, for both existing Azure Pipelines and GitHub integrations

**Comment by furi0us333** [comment]
User story added https://github.com/phylum-dev/roadmap/issues/182
