### ISSUE TITLE
Support Azure Pipelines CI triggers

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#149]
## Overview

**Is your feature request related to a problem? Please describe.**
The current Azure Pipelines CI implementation is meant to handle [PR triggers in Azure Repos git repositories](https://learn.microsoft.com/azure/devops/pipelines/repos/azure-repos-git#pr-triggers) only. There are times when it would be nice to handle CI triggers as well.

**Describe the solution you'd like**
Azure Pipelines CI triggers should be handled such that a simple pass/fail status is provided for all commits to any branch. The pipeline configuration should be able to limit/filter the branches within [YAML config](https://learn.microsoft.com/azure/devops/pipelines/yaml-schema/trigger). The output should be limited to logs since there will not be a Pull Request (PR) available to post comments. The Phylum analysis should be capable of detecting and then working in either a CI or PR trigger context.

**Describe alternatives you've considered**
Creating a separate/distinct integration for CI triggers in Azure Pipelines environments.

## Additional context

The equivalent feature, but for GitLab, was added with #132.

* [Events that trigger pipelines](https://learn.microsoft.com/azure/devops/pipelines/build/triggers)
  * Support for CI triggers in Azure Repos Git should be supported now
  * Support for CI triggers in GitHub should be supported when/if GitHub support is added (#148)
* [Trigger YAML definition](https://learn.microsoft.com/azure/devops/pipelines/yaml-schema/trigger)

## Acceptance criteria

- [x] Azure Pipelines integration detects and handles both PR and CI triggers
- [x] Documentation is updated

**Comment by furi0us333** [comment]
https://github.com/phylum-dev/roadmap/issues/208
