### ISSUE TITLE
Enable Dependabot for GitHub Actions and Python dependencies

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#17]
## Description

GitHub Actions (GHA) are in use for workflows in this repository. They are all currently pinned to a major version. There is a feature that GitHub offers, via Dependabot, to automatically notify when a new version/release of a GHA is available. This issue is to make use of that feature so that GHAs don't fall behind.

Do the same thing for Python dependencies.

## Additional Details

* GitHub documentation for [keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot)
* Confer with others and decide on a schedule
  * Daily seems too often, perhaps weekly or monthly

## Acceptance Criteria

- [x] Dependabot is set up to alert when there are newer versions of GitHub Actions to use in the repository
- [x] Dependabot is set up to alert when there are newer Python dependencies
- [x] Documentation is updated

**Comment by kylewillmon** [comment]
I vote weekly.

Also, whether in this issue or a new issue, we should consider enabling dependabot for our Python dependencies as well.
