### ISSUE TITLE
Allow non-legacy minisign signatures

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/phylum-ci#27]
As mentioned in [this comment](https://github.com/phylum-dev/cli/issues/266#issuecomment-1111426370), the code to validate minisign signatures is intentionally not forward-compatible.

This needs to be changed so that the CLI can begin using non-legacy signatures.

**Comment by maxrake** [comment]
With the completion of phylum-dev/cli#724, the next release of the Phylum CLI will be signed with openssl. It will also be signed with minisign, but that will be phased out over time. This issue is likely OBE and can be closed once minisign is completely phased out.

**Comment by kylewillmon** [comment]
> This issue is likely OBE and can be closed once minisign is completely phased out.

I don't think it's necessary to wait until it's completely phased out. We can already say that we will never switch to non-legacy minisign signatures.
