### ISSUE TITLE
Add support for pnpm

### ISSUE THREAD

**Issue by croe-voxtur** [phylum-dev/phylum-ci#270]
## Overview

**Is your feature request related to a problem? Please describe.**
We are a shop that has about half our code base in Javascript/Typescript.  We sawitched from using [yarn](https://yarnpkg.com/) to [pnpm](https://pnpm.io/) because it is more disk-efficient.  Unfortuantely Phylum doesn't recognize the pnpm lock file.

**Describe the solution you'd like**
Add support for the pnpm lock file (`pnpm-lock.yaml`).

**Describe alternatives you've considered**
We are just looking at phylum at the moment, so to get it to work, I've had to manually run yarn or npm and commit those lock-files instead.

## Acceptance criteria

- [ ] detects and processes `pnpm-lock.yaml` just like it does for `npm` and `yarn` lock files.

**Comment by kylewillmon** [comment]
Thanks for bringing this up!

Lockfile parsing occurs in [our CLI](https://github.com/phylum-dev/cli), so I've created phylum-dev/cli#1138 to track adding support for pnpm

**Comment by maxrake** [comment]
I'll keep this issue open as well...to account for any changes that may be needed in `phylum-ci` to make use of the `pnpm-lock.yaml` parser when it is available. That may just mean adding it to the list of supported lockfiles for automatic lockfile detection...assuming #244 is not completed before then.

**Comment by cd-work** [comment]
Hi! Support for `pnpm` was just added to the latest CLI.

If you want to test it out, you can compile the latest CLI and try to analyze your `pnpm` projects locally:
https://github.com/phylum-dev/cli

**Comment by maxrake** [comment]
@croe-voxtur, a `phylum-ci` release with the associated Docker image updates was just made. It contains the changes needed to support `pnpm` lockfiles.
