### ISSUE TITLE
Add support for Python pre-commit hook integration

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#35]
**Description**
The `phylum` Python package should be updated to offer the ability to analyze lockfile changes within a Python-based pre-commit hook invocation.

**Additional Details**
* Changes to a lockfile in the staged files list should trigger analysis and exit nonzero when any risk threshold is not met
* Expose the functionality in the form of a hook that other `pre-commit` users can reference
* The scope of this work is for **Python** based pre-commit hooks, specifically the [`pre-commit` project](https://pre-commit.com/)
* References/Inspiration
  * [`pre-commit` documentation](https://pre-commit.com/)
    * > The hook must exit nonzero on failure or modify files.
    * > If you are writing your own custom hook, your hook should expect to receive the [`args`](https://pre-commit.com/index.html#config-args) value and then a list of staged files.
  * [hadolint integrations](https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md)
  * [pip-audit](https://pypi.org/project/pip-audit/)

**Acceptance Criteria**
- [x] The `phylum-ci` package offers the ability to analyze lockfile changes when invoked by a pre-commit hook
- [x] Documentation is updated

**Comment by kylewillmon** [comment]
I would recommend creating the hook, but not referencing the [`pre-commit`](https://pre-commit.com/) project.

Projects that use commit hooks configure them in many different ways. Javascript projects, for example, may choose to use [`husky`](https://typicode.github.io/husky/#/) instead. And there are many many alternatives.

Providing the hook script allows users to import that script into whatever solution they choose based on the documentation provided by the configuration provider.

**Comment by maxrake** [comment]
@kylewillmon and I talked about this issue offline and agreed that it would be acceptable to re-scope it to be an integration _specifically_ for the Python [pre-commit](https://pre-commit.com) project. Other hook platforms (or even just the basic `git` hook) will mean separate issues. Making that change now...
