### ISSUE TITLE
Use a single character for "single dash" options

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#56]
## Overview

**Is your feature request related to a problem? Please describe.**
As brought up in [a comment on PR for #55](https://github.com/phylum-dev/phylum-ci/pull/55#discussion_r884990622), the `phylum-ci` options include flags that are specified with more than one character. For instance, `-fa` for `--force-analysis` and `-fi` for `--force-install`. This means it is not possible to chain them together since that would not parse:

```sh
❯ poetry run phylum-ci -fafir 3.4.0 -l poetry.lock
 [+] Extra arguments provided. Assuming a Python `pre-commit` working environment.
 [+] Confirming pre-requisites ...
 [+] Existing `.phylum_project` file found at: /Users/coggins/dev/phylum/phylum-ci/.phylum_project
 [+] `git` binary found on the PATH
 [!] Unrecognized arguments: -fafir 3.4.0

✖ 1 ❯ poetry run phylum-ci -fafi -l poetry.lock
 [+] Extra arguments provided. Assuming a Python `pre-commit` working environment.
 [+] Confirming pre-requisites ...
 [+] Existing `.phylum_project` file found at: /Users/coggins/dev/phylum/phylum-ci/.phylum_project
 [+] `git` binary found on the PATH
 [!] Unrecognized arguments: -fafi

✖ 1 ❯ poetry run phylum-ci -fa -fi -l poetry.lock
 [+] No CI environment detected
 [+] Confirming pre-requisites ...
 [+] Existing `.phylum_project` file found at: /Users/coggins/dev/phylum/phylum-ci/.phylum_project
 [+] `git` binary found on the PATH
 [+] Existing `.git` directory was found at the current working directory
 [+] All pre-requisites met
 [+] lockfile in use: /Users/coggins/dev/phylum/phylum-ci/poetry.lock
 [+] `--force-analysis` flag specified. Proceeding with analysis ...
 [+] phylum_label: phylum-ci_No-CI_main_3a482fbcb2255c3e8784cf637a9cd5dc763d6bf6
 [+] Existing Phylum CLI instance found: v3.5.0 at /Users/coggins/.local/bin/phylum
 [+] Using Phylum CLI instance: v3.5.0 at /Users/coggins/.local/bin/phylum
 [*] Performing analysis ...
 [+] Only considering newly added dependencies ...
 [+] New dependencies: set()
 [+] 0 newly added dependencies
 [+] The analysis is complete and there were NO failures
 [+] Project URL: https://app.phylum.io/projects/e6ddb53a-f600-405e-b8ab-e691a61a0c76?label=phylum-ci_No-CI_main_3a482fbcb2255c3e8784cf637a9cd5dc763d6bf6
 [-] Return code: 0
 [+] Analysis output:
---TRIMMED---
```

Instead, the options have to be provided with spaces between them. This works but does not follow standard conventions for CLI tools.

**Describe the solution you'd like**
Use a single character for all "single dash" options. This would include not just the flags, but also the options that take a value (e.g., the risk domain threshold options).

**Describe alternatives you've considered**
* Don't provide short form options
  * This may be possible for some options that are less frequently used
  * It will be harder for the risk domain threshold options since they are likely to be used much more frequently and as a whole (all five together)...which would mean significantly longer command invocations

## Additional context

For `--vul-threshold`, the short form should NOT be `-v` since that will be used in #23 to represent the standard `--verbose` option to control logging. Consider `-u` instead.

This issue represents a breaking change and it might be the case that users are already entrenched with the current option names. On the other hand, the project is still [zero-ver](https://0ver.org/) and subject to breaking changes. Perhaps @furi0us333 and/or @peterjmorgan can let us know how many folks may already be using this package (for the GitLab integration) and specifically the single dash options...and if now is a better time than not to make a change.

## Acceptance criteria

- [x] All short form options that use a single dash use only a single character
- [x] Documentation is updated

**Comment by furi0us333** [comment]
@maxrake I do not think you will interrupt any users, so feel free to make whatever changes you think are best.
